import ReactPDF from '@react-pdf/renderer';
import React from 'react';
import { Document, Page, Text, View, StyleSheet } from '@react-pdf/renderer';
import { getServerUser } from '../../../../lib/auth';

const styles = StyleSheet.create({
  page: {
    padding: 54,
    paddingTop: 44,
    paddingBottom: 50,
    fontFamily: 'Times-Roman',
    fontSize: 11,
    lineHeight: 1.5,
    color: '#1a1a1a',
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    borderBottomWidth: 0.8,
    borderBottomColor: '#333',
    paddingBottom: 6,
    marginBottom: 18,
  },
  headerLeft: {
    flex: 1,
  },
  headerRight: {
    textAlign: 'right',
  },
  headerName: {
    fontSize: 9,
    color: '#555',
  },
  headerAffiliation: {
    fontSize: 9,
    color: '#555',
    marginTop: 1,
  },
  title: {
    fontSize: 16,
    fontFamily: 'Times-Bold',
    textAlign: 'center',
    marginBottom: 20,
    lineHeight: 1.35,
  },
  sectionTitle: {
    fontSize: 12,
    fontFamily: 'Times-Bold',
    marginTop: 16,
    marginBottom: 8,
    borderBottomWidth: 0.5,
    borderBottomColor: '#aaa',
    paddingBottom: 2,
  },
  paragraph: {
    fontSize: 11,
    lineHeight: 1.55,
    textAlign: 'justify',
    marginBottom: 6,
  },
  footer: {
    position: 'absolute',
    bottom: 28,
    left: 54,
    right: 54,
    textAlign: 'center',
    fontSize: 7.5,
    color: '#bbb',
  },
  pageNumber: {
    position: 'absolute',
    bottom: 28,
    right: 54,
    fontSize: 9,
    color: '#999',
  },
});

interface ProposalContent {
  title: string;
  background: string;
  research_questions: string;
  methodology: string;
  significance: string;
  timeline: string;
}

const SECTION_TITLES: Record<string, string> = {
  background: '1. Background and Literature Review',
  research_questions: '2. Research Questions and Objectives',
  methodology: '3. Research Methodology',
  significance: '4. Significance and Contribution',
  timeline: '5. Timeline and Milestones',
};

function renderParagraphs(text: string) {
  return text
    .split(/\n\n+/)
    .filter(p => p.trim())
    .map((p, i) =>
      React.createElement(Text, { key: i, style: styles.paragraph }, p.trim())
    );
}

function ResearchProposalPDF({
  proposal,
  studentName,
  professorName,
  professorUniversity,
}: {
  proposal: ProposalContent;
  studentName?: string;
  professorName?: string;
  professorUniversity?: string;
}) {
  const sections = ['background', 'research_questions', 'methodology', 'significance', 'timeline'] as const;

  return React.createElement(Document, null,
    React.createElement(Page, { size: 'A4', style: styles.page },
      // Header
      React.createElement(View, { style: styles.header },
        React.createElement(View, { style: styles.headerLeft },
          studentName
            ? React.createElement(Text, { style: styles.headerName }, studentName)
            : null,
        ),
        React.createElement(View, { style: styles.headerRight },
          professorName
            ? React.createElement(Text, { style: styles.headerName }, `Supervisor: ${professorName}`)
            : null,
          professorUniversity
            ? React.createElement(Text, { style: styles.headerAffiliation }, professorUniversity)
            : null,
        ),
      ),

      // Title
      React.createElement(Text, { style: styles.title }, proposal.title),

      // Sections
      ...sections.map(key =>
        React.createElement(View, { key, wrap: false },
          React.createElement(Text, { style: styles.sectionTitle }, SECTION_TITLES[key]),
          ...renderParagraphs(proposal[key] || ''),
        )
      ),

      // Footer
      React.createElement(Text, { style: styles.footer, fixed: true },
        'Generated by Koala PhD · koalaphd.com'
      ),
      React.createElement(Text, {
        style: styles.pageNumber,
        fixed: true,
        render: ({ pageNumber, totalPages }: { pageNumber: number; totalPages: number }) => `${pageNumber} / ${totalPages}`,
      }),
    )
  );
}

export async function POST(req: Request) {
  try {
    const user = await getServerUser();
    if (!user) return Response.json({ error: '请先登录' }, { status: 401 });

    const { proposal, studentName, professorName, professorUniversity } = await req.json() as {
      proposal: ProposalContent;
      studentName?: string;
      professorName?: string;
      professorUniversity?: string;
    };

    if (!proposal || !proposal.title || !proposal.background) {
      return Response.json({ error: 'Invalid proposal data' }, { status: 400 });
    }

    const element = React.createElement(ResearchProposalPDF, {
      proposal,
      studentName,
      professorName,
      professorUniversity,
    });

    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const pdfStream = await ReactPDF.renderToStream(element as any);

    const chunks: Buffer[] = [];
    for await (const chunk of pdfStream) {
      chunks.push(Buffer.from(chunk));
    }
    const pdfBuffer = Buffer.concat(chunks);

    const filename = `Research_Proposal_${(professorName ?? 'draft').replace(/\s+/g, '_')}_${new Date().toISOString().slice(0, 10)}.pdf`;

    return new Response(pdfBuffer, {
      headers: {
        'Content-Type': 'application/pdf',
        'Content-Disposition': `attachment; filename="${filename}"`,
      },
    });
  } catch (e) {
    console.error('[research-proposal/pdf]', e);
    return Response.json({ error: 'PDF generation failed' }, { status: 500 });
  }
}
